// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pdf.proto
// Protobuf C++ Version: 6.33.5

#ifndef pdf_2eproto_2epb_2eh
#define pdf_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_pdf_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_pdf_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_pdf_2eproto;
}  // extern "C"
class Catalog;
struct CatalogDefaultTypeInternal;
extern CatalogDefaultTypeInternal _Catalog_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Catalog_class_data_;
class IndirectObject;
struct IndirectObjectDefaultTypeInternal;
extern IndirectObjectDefaultTypeInternal _IndirectObject_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull IndirectObject_class_data_;
class Page;
struct PageDefaultTypeInternal;
extern PageDefaultTypeInternal _Page_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Page_class_data_;
class PageTree;
struct PageTreeDefaultTypeInternal;
extern PageTreeDefaultTypeInternal _PageTree_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PageTree_class_data_;
class PdfDocument;
struct PdfDocumentDefaultTypeInternal;
extern PdfDocumentDefaultTypeInternal _PdfDocument_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull PdfDocument_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class PageTree final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PageTree) */ {
 public:
  inline PageTree() : PageTree(nullptr) {}
  ~PageTree() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PageTree* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PageTree));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PageTree(::google::protobuf::internal::ConstantInitialized);

  inline PageTree(const PageTree& from) : PageTree(nullptr, from) {}
  inline PageTree(PageTree&& from) noexcept
      : PageTree(nullptr, ::std::move(from)) {}
  inline PageTree& operator=(const PageTree& from) {
    CopyFrom(from);
    return *this;
  }
  inline PageTree& operator=(PageTree&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PageTree& default_instance() {
    return *reinterpret_cast<const PageTree*>(
        &_PageTree_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PageTree& a, PageTree& b) { a.Swap(&b); }
  inline void Swap(PageTree* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PageTree* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PageTree* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PageTree>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PageTree& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PageTree& from) { PageTree::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PageTree* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PageTree"; }

  explicit PageTree(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PageTree(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PageTree& from);
  PageTree(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PageTree&& from) noexcept
      : PageTree(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kKidsFieldNumber = 1,
  };
  // repeated uint32 kids = 1;
  int kids_size() const;
  private:
  int _internal_kids_size() const;

  public:
  void clear_kids() ;
  ::uint32_t kids(int index) const;
  void set_kids(int index, ::uint32_t value);
  void add_kids(::uint32_t value);
  const ::google::protobuf::RepeatedField<::uint32_t>& kids() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL mutable_kids();

  private:
  const ::google::protobuf::RepeatedField<::uint32_t>& _internal_kids() const;
  ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL _internal_mutable_kids();

  public:
  // @@protoc_insertion_point(class_scope:PageTree)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PageTree& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedField<::uint32_t> kids_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pdf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PageTree_class_data_;
// -------------------------------------------------------------------

class Page final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Page) */ {
 public:
  inline Page() : Page(nullptr) {}
  ~Page() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Page* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Page));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Page(::google::protobuf::internal::ConstantInitialized);

  inline Page(const Page& from) : Page(nullptr, from) {}
  inline Page(Page&& from) noexcept
      : Page(nullptr, ::std::move(from)) {}
  inline Page& operator=(const Page& from) {
    CopyFrom(from);
    return *this;
  }
  inline Page& operator=(Page&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Page& default_instance() {
    return *reinterpret_cast<const Page*>(
        &_Page_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Page& a, Page& b) { a.Swap(&b); }
  inline void Swap(Page* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Page* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Page* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Page>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Page& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Page& from) { Page::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Page* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Page"; }

  explicit Page(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Page(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Page& from);
  Page(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Page&& from) noexcept
      : Page(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kParentRefFieldNumber = 3,
    kWidthFieldNumber = 1,
    kHeightFieldNumber = 2,
  };
  // optional uint32 parent_ref = 3;
  bool has_parent_ref() const;
  void clear_parent_ref() ;
  ::uint32_t parent_ref() const;
  void set_parent_ref(::uint32_t value);

  private:
  ::uint32_t _internal_parent_ref() const;
  void _internal_set_parent_ref(::uint32_t value);

  public:
  // optional float width = 1 [default = 612];
  bool has_width() const;
  void clear_width() ;
  float width() const;
  void set_width(float value);

  private:
  float _internal_width() const;
  void _internal_set_width(float value);

  public:
  // optional float height = 2 [default = 792];
  bool has_height() const;
  void clear_height() ;
  float height() const;
  void set_height(float value);

  private:
  float _internal_height() const;
  void _internal_set_height(float value);

  public:
  // @@protoc_insertion_point(class_scope:Page)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Page& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t parent_ref_;
    float width_;
    float height_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pdf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Page_class_data_;
// -------------------------------------------------------------------

class Catalog final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Catalog) */ {
 public:
  inline Catalog() : Catalog(nullptr) {}
  ~Catalog() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Catalog* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Catalog));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Catalog(::google::protobuf::internal::ConstantInitialized);

  inline Catalog(const Catalog& from) : Catalog(nullptr, from) {}
  inline Catalog(Catalog&& from) noexcept
      : Catalog(nullptr, ::std::move(from)) {}
  inline Catalog& operator=(const Catalog& from) {
    CopyFrom(from);
    return *this;
  }
  inline Catalog& operator=(Catalog&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Catalog& default_instance() {
    return *reinterpret_cast<const Catalog*>(
        &_Catalog_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Catalog& a, Catalog& b) { a.Swap(&b); }
  inline void Swap(Catalog* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Catalog* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Catalog* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Catalog>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Catalog& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Catalog& from) { Catalog::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Catalog* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Catalog"; }

  explicit Catalog(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Catalog(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Catalog& from);
  Catalog(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Catalog&& from) noexcept
      : Catalog(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPagesRefFieldNumber = 1,
  };
  // required uint32 pages_ref = 1;
  bool has_pages_ref() const;
  void clear_pages_ref() ;
  ::uint32_t pages_ref() const;
  void set_pages_ref(::uint32_t value);

  private:
  ::uint32_t _internal_pages_ref() const;
  void _internal_set_pages_ref(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Catalog)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Catalog& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t pages_ref_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pdf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Catalog_class_data_;
// -------------------------------------------------------------------

class PdfDocument final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:PdfDocument) */ {
 public:
  inline PdfDocument() : PdfDocument(nullptr) {}
  ~PdfDocument() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PdfDocument* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PdfDocument));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PdfDocument(::google::protobuf::internal::ConstantInitialized);

  inline PdfDocument(const PdfDocument& from) : PdfDocument(nullptr, from) {}
  inline PdfDocument(PdfDocument&& from) noexcept
      : PdfDocument(nullptr, ::std::move(from)) {}
  inline PdfDocument& operator=(const PdfDocument& from) {
    CopyFrom(from);
    return *this;
  }
  inline PdfDocument& operator=(PdfDocument&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PdfDocument& default_instance() {
    return *reinterpret_cast<const PdfDocument*>(
        &_PdfDocument_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(PdfDocument& a, PdfDocument& b) { a.Swap(&b); }
  inline void Swap(PdfDocument* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PdfDocument* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PdfDocument* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PdfDocument>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PdfDocument& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PdfDocument& from) { PdfDocument::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PdfDocument* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "PdfDocument"; }

  explicit PdfDocument(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  PdfDocument(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const PdfDocument& from);
  PdfDocument(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, PdfDocument&& from) noexcept
      : PdfDocument(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPagesFieldNumber = 1,
  };
  // repeated .Page pages = 1;
  int pages_size() const;
  private:
  int _internal_pages_size() const;

  public:
  void clear_pages() ;
  ::Page* PROTOBUF_NONNULL mutable_pages(int index);
  ::google::protobuf::RepeatedPtrField<::Page>* PROTOBUF_NONNULL mutable_pages();

  private:
  const ::google::protobuf::RepeatedPtrField<::Page>& _internal_pages() const;
  ::google::protobuf::RepeatedPtrField<::Page>* PROTOBUF_NONNULL _internal_mutable_pages();
  public:
  const ::Page& pages(int index) const;
  ::Page* PROTOBUF_NONNULL add_pages();
  const ::google::protobuf::RepeatedPtrField<::Page>& pages() const;
  // @@protoc_insertion_point(class_scope:PdfDocument)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const PdfDocument& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::Page > pages_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pdf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull PdfDocument_class_data_;
// -------------------------------------------------------------------

class IndirectObject final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:IndirectObject) */ {
 public:
  inline IndirectObject() : IndirectObject(nullptr) {}
  ~IndirectObject() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(IndirectObject* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(IndirectObject));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR IndirectObject(::google::protobuf::internal::ConstantInitialized);

  inline IndirectObject(const IndirectObject& from) : IndirectObject(nullptr, from) {}
  inline IndirectObject(IndirectObject&& from) noexcept
      : IndirectObject(nullptr, ::std::move(from)) {}
  inline IndirectObject& operator=(const IndirectObject& from) {
    CopyFrom(from);
    return *this;
  }
  inline IndirectObject& operator=(IndirectObject&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IndirectObject& default_instance() {
    return *reinterpret_cast<const IndirectObject*>(
        &_IndirectObject_default_instance_);
  }
  enum BodyCase {
    kCatalog = 2,
    kPageTree = 3,
    kPage = 4,
    BODY_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(IndirectObject& a, IndirectObject& b) { a.Swap(&b); }
  inline void Swap(IndirectObject* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IndirectObject* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IndirectObject* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<IndirectObject>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const IndirectObject& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const IndirectObject& from) { IndirectObject::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(IndirectObject* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "IndirectObject"; }

  explicit IndirectObject(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  IndirectObject(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const IndirectObject& from);
  IndirectObject(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, IndirectObject&& from) noexcept
      : IndirectObject(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNumberFieldNumber = 1,
    kCatalogFieldNumber = 2,
    kPageTreeFieldNumber = 3,
    kPageFieldNumber = 4,
  };
  // required uint32 number = 1;
  bool has_number() const;
  void clear_number() ;
  ::uint32_t number() const;
  void set_number(::uint32_t value);

  private:
  ::uint32_t _internal_number() const;
  void _internal_set_number(::uint32_t value);

  public:
  // .Catalog catalog = 2;
  bool has_catalog() const;
  private:
  bool _internal_has_catalog() const;

  public:
  void clear_catalog() ;
  const ::Catalog& catalog() const;
  [[nodiscard]] ::Catalog* PROTOBUF_NULLABLE release_catalog();
  ::Catalog* PROTOBUF_NONNULL mutable_catalog();
  void set_allocated_catalog(::Catalog* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_catalog(::Catalog* PROTOBUF_NULLABLE value);
  ::Catalog* PROTOBUF_NULLABLE unsafe_arena_release_catalog();

  private:
  const ::Catalog& _internal_catalog() const;
  ::Catalog* PROTOBUF_NONNULL _internal_mutable_catalog();

  public:
  // .PageTree page_tree = 3;
  bool has_page_tree() const;
  private:
  bool _internal_has_page_tree() const;

  public:
  void clear_page_tree() ;
  const ::PageTree& page_tree() const;
  [[nodiscard]] ::PageTree* PROTOBUF_NULLABLE release_page_tree();
  ::PageTree* PROTOBUF_NONNULL mutable_page_tree();
  void set_allocated_page_tree(::PageTree* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_page_tree(::PageTree* PROTOBUF_NULLABLE value);
  ::PageTree* PROTOBUF_NULLABLE unsafe_arena_release_page_tree();

  private:
  const ::PageTree& _internal_page_tree() const;
  ::PageTree* PROTOBUF_NONNULL _internal_mutable_page_tree();

  public:
  // .Page page = 4;
  bool has_page() const;
  private:
  bool _internal_has_page() const;

  public:
  void clear_page() ;
  const ::Page& page() const;
  [[nodiscard]] ::Page* PROTOBUF_NULLABLE release_page();
  ::Page* PROTOBUF_NONNULL mutable_page();
  void set_allocated_page(::Page* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_page(::Page* PROTOBUF_NULLABLE value);
  ::Page* PROTOBUF_NULLABLE unsafe_arena_release_page();

  private:
  const ::Page& _internal_page() const;
  ::Page* PROTOBUF_NONNULL _internal_mutable_page();

  public:
  void clear_body();
  BodyCase body_case() const;
  // @@protoc_insertion_point(class_scope:IndirectObject)
 private:
  class _Internal;
  void set_has_catalog();
  void set_has_page_tree();
  void set_has_page();
  inline bool has_body() const;
  inline void clear_has_body();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 4,
                                   3, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const IndirectObject& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t number_;
    union BodyUnion {
      constexpr BodyUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE catalog_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE page_tree_;
      ::google::protobuf::Message* PROTOBUF_NULLABLE page_;
    } body_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_pdf_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull IndirectObject_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Catalog

// required uint32 pages_ref = 1;
inline bool Catalog::has_pages_ref() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void Catalog::clear_pages_ref() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pages_ref_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t Catalog::pages_ref() const {
  // @@protoc_insertion_point(field_get:Catalog.pages_ref)
  return _internal_pages_ref();
}
inline void Catalog::set_pages_ref(::uint32_t value) {
  _internal_set_pages_ref(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Catalog.pages_ref)
}
inline ::uint32_t Catalog::_internal_pages_ref() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pages_ref_;
}
inline void Catalog::_internal_set_pages_ref(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pages_ref_ = value;
}

// -------------------------------------------------------------------

// PageTree

// repeated uint32 kids = 1;
inline int PageTree::_internal_kids_size() const {
  return _internal_kids().size();
}
inline int PageTree::kids_size() const {
  return _internal_kids_size();
}
inline void PageTree::clear_kids() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.kids_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t PageTree::kids(int index) const {
  // @@protoc_insertion_point(field_get:PageTree.kids)
  return _internal_kids().Get(index);
}
inline void PageTree::set_kids(int index, ::uint32_t value) {
  _internal_mutable_kids()->Set(index, value);
  // @@protoc_insertion_point(field_set:PageTree.kids)
}
inline void PageTree::add_kids(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_kids()->Add(value);
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:PageTree.kids)
}
inline const ::google::protobuf::RepeatedField<::uint32_t>& PageTree::kids() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:PageTree.kids)
  return _internal_kids();
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL PageTree::mutable_kids()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:PageTree.kids)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_kids();
}
inline const ::google::protobuf::RepeatedField<::uint32_t>&
PageTree::_internal_kids() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.kids_;
}
inline ::google::protobuf::RepeatedField<::uint32_t>* PROTOBUF_NONNULL
PageTree::_internal_mutable_kids() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.kids_;
}

// -------------------------------------------------------------------

// Page

// optional float width = 1 [default = 612];
inline bool Page::has_width() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Page::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 612;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline float Page::width() const {
  // @@protoc_insertion_point(field_get:Page.width)
  return _internal_width();
}
inline void Page::set_width(float value) {
  _internal_set_width(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:Page.width)
}
inline float Page::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void Page::_internal_set_width(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// optional float height = 2 [default = 792];
inline bool Page::has_height() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void Page::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 792;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline float Page::height() const {
  // @@protoc_insertion_point(field_get:Page.height)
  return _internal_height();
}
inline void Page::set_height(float value) {
  _internal_set_height(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Page.height)
}
inline float Page::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void Page::_internal_set_height(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

// optional uint32 parent_ref = 3;
inline bool Page::has_parent_ref() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void Page::clear_parent_ref() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parent_ref_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t Page::parent_ref() const {
  // @@protoc_insertion_point(field_get:Page.parent_ref)
  return _internal_parent_ref();
}
inline void Page::set_parent_ref(::uint32_t value) {
  _internal_set_parent_ref(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:Page.parent_ref)
}
inline ::uint32_t Page::_internal_parent_ref() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.parent_ref_;
}
inline void Page::_internal_set_parent_ref(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.parent_ref_ = value;
}

// -------------------------------------------------------------------

// IndirectObject

// required uint32 number = 1;
inline bool IndirectObject::has_number() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void IndirectObject::clear_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t IndirectObject::number() const {
  // @@protoc_insertion_point(field_get:IndirectObject.number)
  return _internal_number();
}
inline void IndirectObject::set_number(::uint32_t value) {
  _internal_set_number(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:IndirectObject.number)
}
inline ::uint32_t IndirectObject::_internal_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.number_;
}
inline void IndirectObject::_internal_set_number(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.number_ = value;
}

// .Catalog catalog = 2;
inline bool IndirectObject::has_catalog() const {
  return body_case() == kCatalog;
}
inline bool IndirectObject::_internal_has_catalog() const {
  return body_case() == kCatalog;
}
inline void IndirectObject::set_has_catalog() {
  _impl_._oneof_case_[0] = kCatalog;
}
inline void IndirectObject::clear_catalog() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kCatalog) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.catalog_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.catalog_);
    }
    clear_has_body();
  }
}
inline ::Catalog* PROTOBUF_NULLABLE IndirectObject::release_catalog() {
  // @@protoc_insertion_point(field_release:IndirectObject.catalog)
  if (body_case() == kCatalog) {
    clear_has_body();
    auto* temp = reinterpret_cast<::Catalog*>(_impl_.body_.catalog_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.catalog_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Catalog& IndirectObject::_internal_catalog() const {
  return body_case() == kCatalog ? static_cast<const ::Catalog&>(*reinterpret_cast<::Catalog*>(_impl_.body_.catalog_))
                     : reinterpret_cast<const ::Catalog&>(::_Catalog_default_instance_);
}
inline const ::Catalog& IndirectObject::catalog() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:IndirectObject.catalog)
  return _internal_catalog();
}
inline ::Catalog* PROTOBUF_NULLABLE IndirectObject::unsafe_arena_release_catalog() {
  // @@protoc_insertion_point(field_unsafe_arena_release:IndirectObject.catalog)
  if (body_case() == kCatalog) {
    clear_has_body();
    auto* temp = reinterpret_cast<::Catalog*>(_impl_.body_.catalog_);
    _impl_.body_.catalog_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void IndirectObject::unsafe_arena_set_allocated_catalog(
    ::Catalog* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_body();
  if (value) {
    set_has_catalog();
    _impl_.body_.catalog_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:IndirectObject.catalog)
}
inline ::Catalog* PROTOBUF_NONNULL IndirectObject::_internal_mutable_catalog() {
  if (body_case() != kCatalog) {
    clear_body();
    set_has_catalog();
    _impl_.body_.catalog_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Catalog>(GetArena()));
  }
  return reinterpret_cast<::Catalog*>(_impl_.body_.catalog_);
}
inline ::Catalog* PROTOBUF_NONNULL IndirectObject::mutable_catalog()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Catalog* _msg = _internal_mutable_catalog();
  // @@protoc_insertion_point(field_mutable:IndirectObject.catalog)
  return _msg;
}

// .PageTree page_tree = 3;
inline bool IndirectObject::has_page_tree() const {
  return body_case() == kPageTree;
}
inline bool IndirectObject::_internal_has_page_tree() const {
  return body_case() == kPageTree;
}
inline void IndirectObject::set_has_page_tree() {
  _impl_._oneof_case_[0] = kPageTree;
}
inline void IndirectObject::clear_page_tree() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPageTree) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.page_tree_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.page_tree_);
    }
    clear_has_body();
  }
}
inline ::PageTree* PROTOBUF_NULLABLE IndirectObject::release_page_tree() {
  // @@protoc_insertion_point(field_release:IndirectObject.page_tree)
  if (body_case() == kPageTree) {
    clear_has_body();
    auto* temp = reinterpret_cast<::PageTree*>(_impl_.body_.page_tree_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.page_tree_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::PageTree& IndirectObject::_internal_page_tree() const {
  return body_case() == kPageTree ? static_cast<const ::PageTree&>(*reinterpret_cast<::PageTree*>(_impl_.body_.page_tree_))
                     : reinterpret_cast<const ::PageTree&>(::_PageTree_default_instance_);
}
inline const ::PageTree& IndirectObject::page_tree() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:IndirectObject.page_tree)
  return _internal_page_tree();
}
inline ::PageTree* PROTOBUF_NULLABLE IndirectObject::unsafe_arena_release_page_tree() {
  // @@protoc_insertion_point(field_unsafe_arena_release:IndirectObject.page_tree)
  if (body_case() == kPageTree) {
    clear_has_body();
    auto* temp = reinterpret_cast<::PageTree*>(_impl_.body_.page_tree_);
    _impl_.body_.page_tree_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void IndirectObject::unsafe_arena_set_allocated_page_tree(
    ::PageTree* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_body();
  if (value) {
    set_has_page_tree();
    _impl_.body_.page_tree_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:IndirectObject.page_tree)
}
inline ::PageTree* PROTOBUF_NONNULL IndirectObject::_internal_mutable_page_tree() {
  if (body_case() != kPageTree) {
    clear_body();
    set_has_page_tree();
    _impl_.body_.page_tree_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::PageTree>(GetArena()));
  }
  return reinterpret_cast<::PageTree*>(_impl_.body_.page_tree_);
}
inline ::PageTree* PROTOBUF_NONNULL IndirectObject::mutable_page_tree()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::PageTree* _msg = _internal_mutable_page_tree();
  // @@protoc_insertion_point(field_mutable:IndirectObject.page_tree)
  return _msg;
}

// .Page page = 4;
inline bool IndirectObject::has_page() const {
  return body_case() == kPage;
}
inline bool IndirectObject::_internal_has_page() const {
  return body_case() == kPage;
}
inline void IndirectObject::set_has_page() {
  _impl_._oneof_case_[0] = kPage;
}
inline void IndirectObject::clear_page() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (body_case() == kPage) {
    if (GetArena() == nullptr) {
      delete _impl_.body_.page_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.page_);
    }
    clear_has_body();
  }
}
inline ::Page* PROTOBUF_NULLABLE IndirectObject::release_page() {
  // @@protoc_insertion_point(field_release:IndirectObject.page)
  if (body_case() == kPage) {
    clear_has_body();
    auto* temp = reinterpret_cast<::Page*>(_impl_.body_.page_);
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.body_.page_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::Page& IndirectObject::_internal_page() const {
  return body_case() == kPage ? static_cast<const ::Page&>(*reinterpret_cast<::Page*>(_impl_.body_.page_))
                     : reinterpret_cast<const ::Page&>(::_Page_default_instance_);
}
inline const ::Page& IndirectObject::page() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:IndirectObject.page)
  return _internal_page();
}
inline ::Page* PROTOBUF_NULLABLE IndirectObject::unsafe_arena_release_page() {
  // @@protoc_insertion_point(field_unsafe_arena_release:IndirectObject.page)
  if (body_case() == kPage) {
    clear_has_body();
    auto* temp = reinterpret_cast<::Page*>(_impl_.body_.page_);
    _impl_.body_.page_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void IndirectObject::unsafe_arena_set_allocated_page(
    ::Page* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_body();
  if (value) {
    set_has_page();
    _impl_.body_.page_ = reinterpret_cast<::google::protobuf::Message*>(value);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:IndirectObject.page)
}
inline ::Page* PROTOBUF_NONNULL IndirectObject::_internal_mutable_page() {
  if (body_case() != kPage) {
    clear_body();
    set_has_page();
    _impl_.body_.page_ = reinterpret_cast<::google::protobuf::Message*>(
        ::google::protobuf::Message::DefaultConstruct<::Page>(GetArena()));
  }
  return reinterpret_cast<::Page*>(_impl_.body_.page_);
}
inline ::Page* PROTOBUF_NONNULL IndirectObject::mutable_page()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::Page* _msg = _internal_mutable_page();
  // @@protoc_insertion_point(field_mutable:IndirectObject.page)
  return _msg;
}

inline bool IndirectObject::has_body() const {
  return body_case() != BODY_NOT_SET;
}
inline void IndirectObject::clear_has_body() {
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}
inline IndirectObject::BodyCase IndirectObject::body_case() const {
  return IndirectObject::BodyCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// PdfDocument

// repeated .Page pages = 1;
inline int PdfDocument::_internal_pages_size() const {
  return _internal_pages().size();
}
inline int PdfDocument::pages_size() const {
  return _internal_pages_size();
}
inline void PdfDocument::clear_pages() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.pages_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::Page* PROTOBUF_NONNULL PdfDocument::mutable_pages(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:PdfDocument.pages)
  return _internal_mutable_pages()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::Page>* PROTOBUF_NONNULL PdfDocument::mutable_pages()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:PdfDocument.pages)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_pages();
}
inline const ::Page& PdfDocument::pages(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:PdfDocument.pages)
  return _internal_pages().Get(index);
}
inline ::Page* PROTOBUF_NONNULL PdfDocument::add_pages()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::Page* _add =
      _internal_mutable_pages()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:PdfDocument.pages)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::Page>& PdfDocument::pages() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:PdfDocument.pages)
  return _internal_pages();
}
inline const ::google::protobuf::RepeatedPtrField<::Page>&
PdfDocument::_internal_pages() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.pages_;
}
inline ::google::protobuf::RepeatedPtrField<::Page>* PROTOBUF_NONNULL
PdfDocument::_internal_mutable_pages() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.pages_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // pdf_2eproto_2epb_2eh
