// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: pdf.proto
// Protobuf C++ Version: 6.33.5

#include "pdf.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace pdf_proto {

inline constexpr PageTree::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        kids_{} {}

template <typename>
PROTOBUF_CONSTEXPR PageTree::PageTree(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PageTree_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PageTreeDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PageTreeDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PageTreeDefaultTypeInternal() {}
  union {
    PageTree _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PageTreeDefaultTypeInternal _PageTree_default_instance_;

inline constexpr ContentStream::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        raw_content_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filter_{static_cast< ::pdf_proto::ContentStream_FilterType >(0)},
        length_delta_{0},
        skip_compression_{false} {}

template <typename>
PROTOBUF_CONSTEXPR ContentStream::ContentStream(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ContentStream_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ContentStreamDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ContentStreamDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~ContentStreamDefaultTypeInternal() {}
  union {
    ContentStream _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ContentStreamDefaultTypeInternal _ContentStream_default_instance_;

inline constexpr Catalog::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pages_ref_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Catalog::Catalog(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Catalog_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CatalogDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CatalogDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CatalogDefaultTypeInternal() {}
  union {
    Catalog _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CatalogDefaultTypeInternal _Catalog_default_instance_;

inline constexpr Page::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        content_stream_{nullptr},
        parent_ref_{0u},
        width_{612},
        height_{792} {}

template <typename>
PROTOBUF_CONSTEXPR Page::Page(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Page_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PageDefaultTypeInternal() {}
  union {
    Page _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PageDefaultTypeInternal _Page_default_instance_;

inline constexpr PdfDocument::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        pages_{} {}

template <typename>
PROTOBUF_CONSTEXPR PdfDocument::PdfDocument(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(PdfDocument_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PdfDocumentDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PdfDocumentDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PdfDocumentDefaultTypeInternal() {}
  union {
    PdfDocument _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PdfDocumentDefaultTypeInternal _PdfDocument_default_instance_;

inline constexpr IndirectObject::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        number_{0u},
        body_{},
        _oneof_case_{} {}

template <typename>
PROTOBUF_CONSTEXPR IndirectObject::IndirectObject(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(IndirectObject_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct IndirectObjectDefaultTypeInternal {
  PROTOBUF_CONSTEXPR IndirectObjectDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~IndirectObjectDefaultTypeInternal() {}
  union {
    IndirectObject _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 IndirectObjectDefaultTypeInternal _IndirectObject_default_instance_;
}  // namespace pdf_proto
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_pdf_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_pdf_2eproto = nullptr;
const ::uint32_t
    TableStruct_pdf_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::pdf_proto::Catalog, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::pdf_proto::Catalog, _impl_.pages_ref_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::pdf_proto::PageTree, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::pdf_proto::PageTree, _impl_.kids_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::pdf_proto::ContentStream, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::pdf_proto::ContentStream, _impl_.filter_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::ContentStream, _impl_.raw_content_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::ContentStream, _impl_.length_delta_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::ContentStream, _impl_.skip_compression_),
        1,
        0,
        2,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::pdf_proto::Page, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::pdf_proto::Page, _impl_.width_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::Page, _impl_.height_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::Page, _impl_.parent_ref_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::Page, _impl_.content_stream_),
        2,
        3,
        1,
        0,
        0x085, // bitmap
        PROTOBUF_FIELD_OFFSET(::pdf_proto::IndirectObject, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::IndirectObject, _impl_._oneof_case_[0]),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::pdf_proto::IndirectObject, _impl_.number_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::IndirectObject, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::IndirectObject, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::IndirectObject, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::pdf_proto::IndirectObject, _impl_.body_),
        0,
        ~0u,
        ~0u,
        ~0u,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::pdf_proto::PdfDocument, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::pdf_proto::PdfDocument, _impl_.pages_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::pdf_proto::Catalog)},
        {5, sizeof(::pdf_proto::PageTree)},
        {10, sizeof(::pdf_proto::ContentStream)},
        {21, sizeof(::pdf_proto::Page)},
        {32, sizeof(::pdf_proto::IndirectObject)},
        {45, sizeof(::pdf_proto::PdfDocument)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::pdf_proto::_Catalog_default_instance_._instance,
    &::pdf_proto::_PageTree_default_instance_._instance,
    &::pdf_proto::_ContentStream_default_instance_._instance,
    &::pdf_proto::_Page_default_instance_._instance,
    &::pdf_proto::_IndirectObject_default_instance_._instance,
    &::pdf_proto::_PdfDocument_default_instance_._instance,
};
const char descriptor_table_protodef_pdf_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\tpdf.proto\022\tpdf_proto\"\034\n\007Catalog\022\021\n\tpag"
    "es_ref\030\001 \002(\r\"\030\n\010PageTree\022\014\n\004kids\030\001 \003(\r\"\274"
    "\001\n\rContentStream\0229\n\006filter\030\001 \001(\0162#.pdf_p"
    "roto.ContentStream.FilterType:\004NONE\022\023\n\013r"
    "aw_content\030\002 \001(\014\022\027\n\014length_delta\030\003 \001(\021:\001"
    "0\022\037\n\020skip_compression\030\004 \001(\010:\005false\"!\n\nFi"
    "lterType\022\010\n\004NONE\020\000\022\t\n\005FLATE\020\001\"u\n\004Page\022\022\n"
    "\005width\030\001 \001(\002:\003612\022\023\n\006height\030\002 \001(\002:\003792\022\022"
    "\n\nparent_ref\030\003 \001(\r\0220\n\016content_stream\030\004 \001"
    "(\0132\030.pdf_proto.ContentStream\"\232\001\n\016Indirec"
    "tObject\022\016\n\006number\030\001 \002(\r\022%\n\007catalog\030\002 \001(\013"
    "2\022.pdf_proto.CatalogH\000\022(\n\tpage_tree\030\003 \001("
    "\0132\023.pdf_proto.PageTreeH\000\022\037\n\004page\030\004 \001(\0132\017"
    ".pdf_proto.PageH\000B\006\n\004body\"-\n\013PdfDocument"
    "\022\036\n\005pages\030\001 \003(\0132\017.pdf_proto.Page"
};
static ::absl::once_flag descriptor_table_pdf_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_pdf_2eproto = {
    false,
    false,
    592,
    descriptor_table_protodef_pdf_2eproto,
    "pdf.proto",
    &descriptor_table_pdf_2eproto_once,
    nullptr,
    0,
    6,
    schemas,
    file_default_instances,
    TableStruct_pdf_2eproto::offsets,
    file_level_enum_descriptors_pdf_2eproto,
    file_level_service_descriptors_pdf_2eproto,
};
namespace pdf_proto {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ContentStream_FilterType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_pdf_2eproto);
  return file_level_enum_descriptors_pdf_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ContentStream_FilterType_internal_data_[] = {
    131072u, 0u, };
// ===================================================================

class Catalog::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Catalog>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Catalog, _impl_._has_bits_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

Catalog::Catalog(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Catalog_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pdf_proto.Catalog)
}
Catalog::Catalog(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Catalog& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Catalog_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE Catalog::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void Catalog::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.pages_ref_ = {};
}
Catalog::~Catalog() {
  // @@protoc_insertion_point(destructor:pdf_proto.Catalog)
  SharedDtor(*this);
}
inline void Catalog::SharedDtor(MessageLite& self) {
  Catalog& this_ = static_cast<Catalog&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Catalog::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Catalog(arena);
}
constexpr auto Catalog::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Catalog),
                                            alignof(Catalog));
}
constexpr auto Catalog::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Catalog_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          Catalog::IsInitializedImpl,
          &Catalog::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Catalog>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Catalog::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Catalog>(), &Catalog::ByteSizeLong,
              &Catalog::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Catalog, _impl_._cached_size_),
          false,
      },
      &Catalog::kDescriptorMethods,
      &descriptor_table_pdf_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Catalog_class_data_ =
        Catalog::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Catalog::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Catalog_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Catalog_class_data_.tc_table);
  return Catalog_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
Catalog::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Catalog, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    Catalog_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pdf_proto::Catalog>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required uint32 pages_ref = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Catalog, _impl_.pages_ref_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(Catalog, _impl_.pages_ref_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required uint32 pages_ref = 1;
    {PROTOBUF_FIELD_OFFSET(Catalog, _impl_.pages_ref_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void Catalog::Clear() {
// @@protoc_insertion_point(message_clear_start:pdf_proto.Catalog)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.pages_ref_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Catalog::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Catalog& this_ = static_cast<const Catalog&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Catalog::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Catalog& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:pdf_proto.Catalog)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required uint32 pages_ref = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_pages_ref(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pdf_proto.Catalog)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Catalog::ByteSizeLong(const MessageLite& base) {
  const Catalog& this_ = static_cast<const Catalog&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Catalog::ByteSizeLong() const {
  const Catalog& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pdf_proto.Catalog)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // required uint32 pages_ref = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_pages_ref());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Catalog::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Catalog*>(&to_msg);
  auto& from = static_cast<const Catalog&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:pdf_proto.Catalog)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.pages_ref_ = from._impl_.pages_ref_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Catalog::CopyFrom(const Catalog& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:pdf_proto.Catalog)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool Catalog::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const Catalog&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  return true;
}

void Catalog::InternalSwap(Catalog* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.pages_ref_, other->_impl_.pages_ref_);
}

::google::protobuf::Metadata Catalog::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PageTree::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PageTree>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PageTree, _impl_._has_bits_);
};

PageTree::PageTree(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PageTree_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pdf_proto.PageTree)
}
PROTOBUF_NDEBUG_INLINE PageTree::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::pdf_proto::PageTree& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        kids_{visibility, arena, from.kids_} {}

PageTree::PageTree(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PageTree& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PageTree_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PageTree* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:pdf_proto.PageTree)
}
PROTOBUF_NDEBUG_INLINE PageTree::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        kids_{visibility, arena} {}

inline void PageTree::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PageTree::~PageTree() {
  // @@protoc_insertion_point(destructor:pdf_proto.PageTree)
  SharedDtor(*this);
}
inline void PageTree::SharedDtor(MessageLite& self) {
  PageTree& this_ = static_cast<PageTree&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PageTree::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PageTree(arena);
}
constexpr auto PageTree::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PageTree, _impl_.kids_) +
          decltype(PageTree::_impl_.kids_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(PageTree), alignof(PageTree), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PageTree::PlacementNew_,
                                 sizeof(PageTree),
                                 alignof(PageTree));
  }
}
constexpr auto PageTree::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PageTree_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PageTree::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PageTree>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PageTree::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PageTree>(), &PageTree::ByteSizeLong,
              &PageTree::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PageTree, _impl_._cached_size_),
          false,
      },
      &PageTree::kDescriptorMethods,
      &descriptor_table_pdf_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PageTree_class_data_ =
        PageTree::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PageTree::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PageTree_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PageTree_class_data_.tc_table);
  return PageTree_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
PageTree::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PageTree, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    PageTree_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pdf_proto::PageTree>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated uint32 kids = 1;
    {::_pbi::TcParser::FastV32R1,
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(PageTree, _impl_.kids_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated uint32 kids = 1;
    {PROTOBUF_FIELD_OFFSET(PageTree, _impl_.kids_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void PageTree::Clear() {
// @@protoc_insertion_point(message_clear_start:pdf_proto.PageTree)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.kids_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PageTree::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PageTree& this_ = static_cast<const PageTree&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PageTree::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PageTree& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:pdf_proto.PageTree)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated uint32 kids = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_kids_size(); i < n; ++i) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          1, this_._internal_kids().Get(i), target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pdf_proto.PageTree)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PageTree::ByteSizeLong(const MessageLite& base) {
  const PageTree& this_ = static_cast<const PageTree&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PageTree::ByteSizeLong() const {
  const PageTree& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pdf_proto.PageTree)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated uint32 kids = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      ::size_t data_size = ::_pbi::WireFormatLite::UInt32Size(
          this_._internal_kids());
      ::size_t tag_size = ::size_t{1} *
          ::_pbi::FromIntSize(this_._internal_kids_size());
      total_size += tag_size + data_size;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PageTree::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PageTree*>(&to_msg);
  auto& from = static_cast<const PageTree&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:pdf_proto.PageTree)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_kids()->MergeFrom(from._internal_kids());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PageTree::CopyFrom(const PageTree& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:pdf_proto.PageTree)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PageTree::InternalSwap(PageTree* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.kids_.InternalSwap(&other->_impl_.kids_);
}

::google::protobuf::Metadata PageTree::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ContentStream::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ContentStream>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ContentStream, _impl_._has_bits_);
};

ContentStream::ContentStream(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ContentStream_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pdf_proto.ContentStream)
}
PROTOBUF_NDEBUG_INLINE ContentStream::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::pdf_proto::ContentStream& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        raw_content_(arena, from.raw_content_) {}

ContentStream::ContentStream(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ContentStream& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ContentStream_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ContentStream* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, filter_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, filter_),
           offsetof(Impl_, skip_compression_) -
               offsetof(Impl_, filter_) +
               sizeof(Impl_::skip_compression_));

  // @@protoc_insertion_point(copy_constructor:pdf_proto.ContentStream)
}
PROTOBUF_NDEBUG_INLINE ContentStream::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        raw_content_(arena) {}

inline void ContentStream::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, filter_),
           0,
           offsetof(Impl_, skip_compression_) -
               offsetof(Impl_, filter_) +
               sizeof(Impl_::skip_compression_));
}
ContentStream::~ContentStream() {
  // @@protoc_insertion_point(destructor:pdf_proto.ContentStream)
  SharedDtor(*this);
}
inline void ContentStream::SharedDtor(MessageLite& self) {
  ContentStream& this_ = static_cast<ContentStream&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.raw_content_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ContentStream::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ContentStream(arena);
}
constexpr auto ContentStream::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(ContentStream),
                                            alignof(ContentStream));
}
constexpr auto ContentStream::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ContentStream_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ContentStream::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ContentStream>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ContentStream::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ContentStream>(), &ContentStream::ByteSizeLong,
              &ContentStream::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ContentStream, _impl_._cached_size_),
          false,
      },
      &ContentStream::kDescriptorMethods,
      &descriptor_table_pdf_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull ContentStream_class_data_ =
        ContentStream::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
ContentStream::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&ContentStream_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(ContentStream_class_data_.tc_table);
  return ContentStream_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2>
ContentStream::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(ContentStream, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    ContentStream_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pdf_proto::ContentStream>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional bool skip_compression = 4 [default = false];
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(ContentStream, _impl_.skip_compression_), 3>(),
     {32, 3, 0,
      PROTOBUF_FIELD_OFFSET(ContentStream, _impl_.skip_compression_)}},
    // optional .pdf_proto.ContentStream.FilterType filter = 1 [default = NONE];
    {::_pbi::TcParser::FastEr0S1,
     {8, 1, 1,
      PROTOBUF_FIELD_OFFSET(ContentStream, _impl_.filter_)}},
    // optional bytes raw_content = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 0, 0,
      PROTOBUF_FIELD_OFFSET(ContentStream, _impl_.raw_content_)}},
    // optional sint32 length_delta = 3 [default = 0];
    {::_pbi::TcParser::FastZ32S1,
     {24, 2, 0,
      PROTOBUF_FIELD_OFFSET(ContentStream, _impl_.length_delta_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional .pdf_proto.ContentStream.FilterType filter = 1 [default = NONE];
    {PROTOBUF_FIELD_OFFSET(ContentStream, _impl_.filter_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kEnumRange)},
    // optional bytes raw_content = 2;
    {PROTOBUF_FIELD_OFFSET(ContentStream, _impl_.raw_content_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional sint32 length_delta = 3 [default = 0];
    {PROTOBUF_FIELD_OFFSET(ContentStream, _impl_.length_delta_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kSInt32)},
    // optional bool skip_compression = 4 [default = false];
    {PROTOBUF_FIELD_OFFSET(ContentStream, _impl_.skip_compression_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  {{
      {0, 1},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void ContentStream::Clear() {
// @@protoc_insertion_point(message_clear_start:pdf_proto.ContentStream)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.raw_content_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000eU)) {
    ::memset(&_impl_.filter_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.skip_compression_) -
        reinterpret_cast<char*>(&_impl_.filter_)) + sizeof(_impl_.skip_compression_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ContentStream::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ContentStream& this_ = static_cast<const ContentStream&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ContentStream::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const ContentStream& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:pdf_proto.ContentStream)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .pdf_proto.ContentStream.FilterType filter = 1 [default = NONE];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(
        1, this_._internal_filter(), target);
  }

  // optional bytes raw_content = 2;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_raw_content();
    target = stream->WriteBytesMaybeAliased(2, _s, target);
  }

  // optional sint32 length_delta = 3 [default = 0];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteSInt32ToArray(
        3, this_._internal_length_delta(), target);
  }

  // optional bool skip_compression = 4 [default = false];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        4, this_._internal_skip_compression(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pdf_proto.ContentStream)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ContentStream::ByteSizeLong(const MessageLite& base) {
  const ContentStream& this_ = static_cast<const ContentStream&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ContentStream::ByteSizeLong() const {
  const ContentStream& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pdf_proto.ContentStream)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000008U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x00000007U)) {
    // optional bytes raw_content = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                      this_._internal_raw_content());
    }
    // optional .pdf_proto.ContentStream.FilterType filter = 1 [default = NONE];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 +
                    ::_pbi::WireFormatLite::EnumSize(this_._internal_filter());
    }
    // optional sint32 length_delta = 3 [default = 0];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::SInt32SizePlusOne(
          this_._internal_length_delta());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ContentStream::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<ContentStream*>(&to_msg);
  auto& from = static_cast<const ContentStream&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:pdf_proto.ContentStream)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_raw_content(from._internal_raw_content());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.filter_ = from._impl_.filter_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.length_delta_ = from._impl_.length_delta_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.skip_compression_ = from._impl_.skip_compression_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ContentStream::CopyFrom(const ContentStream& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:pdf_proto.ContentStream)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void ContentStream::InternalSwap(ContentStream* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.raw_content_, &other->_impl_.raw_content_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ContentStream, _impl_.skip_compression_)
      + sizeof(ContentStream::_impl_.skip_compression_)
      - PROTOBUF_FIELD_OFFSET(ContentStream, _impl_.filter_)>(
          reinterpret_cast<char*>(&_impl_.filter_),
          reinterpret_cast<char*>(&other->_impl_.filter_));
}

::google::protobuf::Metadata ContentStream::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Page::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<Page>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Page, _impl_._has_bits_);
};

Page::Page(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Page_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pdf_proto.Page)
}
PROTOBUF_NDEBUG_INLINE Page::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::pdf_proto::Page& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Page::Page(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Page& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Page_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Page* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.content_stream_ = (CheckHasBit(cached_has_bits, 0x00000001U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.content_stream_)
                : nullptr;
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, parent_ref_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, parent_ref_),
           offsetof(Impl_, height_) -
               offsetof(Impl_, parent_ref_) +
               sizeof(Impl_::height_));

  // @@protoc_insertion_point(copy_constructor:pdf_proto.Page)
}
PROTOBUF_NDEBUG_INLINE Page::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        width_{612},
        height_{792} {}

inline void Page::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, content_stream_),
           0,
           offsetof(Impl_, parent_ref_) -
               offsetof(Impl_, content_stream_) +
               sizeof(Impl_::parent_ref_));
}
Page::~Page() {
  // @@protoc_insertion_point(destructor:pdf_proto.Page)
  SharedDtor(*this);
}
inline void Page::SharedDtor(MessageLite& self) {
  Page& this_ = static_cast<Page&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.content_stream_;
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL Page::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Page(arena);
}
constexpr auto Page::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Page),
                                            alignof(Page));
}
constexpr auto Page::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Page_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Page::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Page>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Page::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Page>(), &Page::ByteSizeLong,
              &Page::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Page, _impl_._cached_size_),
          false,
      },
      &Page::kDescriptorMethods,
      &descriptor_table_pdf_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Page_class_data_ =
        Page::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Page::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Page_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Page_class_data_.tc_table);
  return Page_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 1, 0, 2>
Page::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Page, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    Page_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pdf_proto::Page>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional .pdf_proto.ContentStream content_stream = 4;
    {::_pbi::TcParser::FastMtS1,
     {34, 0, 0,
      PROTOBUF_FIELD_OFFSET(Page, _impl_.content_stream_)}},
    // optional float width = 1 [default = 612];
    {::_pbi::TcParser::FastF32S1,
     {13, 2, 0,
      PROTOBUF_FIELD_OFFSET(Page, _impl_.width_)}},
    // optional float height = 2 [default = 792];
    {::_pbi::TcParser::FastF32S1,
     {21, 3, 0,
      PROTOBUF_FIELD_OFFSET(Page, _impl_.height_)}},
    // optional uint32 parent_ref = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Page, _impl_.parent_ref_), 1>(),
     {24, 1, 0,
      PROTOBUF_FIELD_OFFSET(Page, _impl_.parent_ref_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional float width = 1 [default = 612];
    {PROTOBUF_FIELD_OFFSET(Page, _impl_.width_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional float height = 2 [default = 792];
    {PROTOBUF_FIELD_OFFSET(Page, _impl_.height_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kFloat)},
    // optional uint32 parent_ref = 3;
    {PROTOBUF_FIELD_OFFSET(Page, _impl_.parent_ref_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // optional .pdf_proto.ContentStream content_stream = 4;
    {PROTOBUF_FIELD_OFFSET(Page, _impl_.content_stream_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::pdf_proto::ContentStream>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void Page::Clear() {
// @@protoc_insertion_point(message_clear_start:pdf_proto.Page)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    ABSL_DCHECK(_impl_.content_stream_ != nullptr);
    _impl_.content_stream_->Clear();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000eU)) {
    _impl_.parent_ref_ = 0u;
    _impl_.width_ = 612;
    _impl_.height_ = 792;
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Page::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Page& this_ = static_cast<const Page&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Page::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Page& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:pdf_proto.Page)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional float width = 1 [default = 612];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        1, this_._internal_width(), target);
  }

  // optional float height = 2 [default = 792];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(
        2, this_._internal_height(), target);
  }

  // optional uint32 parent_ref = 3;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        3, this_._internal_parent_ref(), target);
  }

  // optional .pdf_proto.ContentStream content_stream = 4;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.content_stream_, this_._impl_.content_stream_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pdf_proto.Page)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Page::ByteSizeLong(const MessageLite& base) {
  const Page& this_ = static_cast<const Page&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Page::ByteSizeLong() const {
  const Page& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pdf_proto.Page)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += ::absl::popcount(0x0000000cU & cached_has_bits) * 5;
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    // optional .pdf_proto.ContentStream content_stream = 4;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.content_stream_);
    }
    // optional uint32 parent_ref = 3;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_parent_ref());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Page::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<Page*>(&to_msg);
  auto& from = static_cast<const Page&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:pdf_proto.Page)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      ABSL_DCHECK(from._impl_.content_stream_ != nullptr);
      if (_this->_impl_.content_stream_ == nullptr) {
        _this->_impl_.content_stream_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.content_stream_);
      } else {
        _this->_impl_.content_stream_->MergeFrom(*from._impl_.content_stream_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.parent_ref_ = from._impl_.parent_ref_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.width_ = from._impl_.width_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.height_ = from._impl_.height_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Page::CopyFrom(const Page& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:pdf_proto.Page)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Page::InternalSwap(Page* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Page, _impl_.height_)
      + sizeof(Page::_impl_.height_)
      - PROTOBUF_FIELD_OFFSET(Page, _impl_.content_stream_)>(
          reinterpret_cast<char*>(&_impl_.content_stream_),
          reinterpret_cast<char*>(&other->_impl_.content_stream_));
}

::google::protobuf::Metadata Page::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class IndirectObject::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<IndirectObject>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(IndirectObject, _impl_._has_bits_);
  static constexpr ::int32_t kOneofCaseOffset =
      PROTOBUF_FIELD_OFFSET(::pdf_proto::IndirectObject, _impl_._oneof_case_);
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000001) ^ 0x00000001) != 0;
  }
};

void IndirectObject::set_allocated_catalog(::pdf_proto::Catalog* PROTOBUF_NULLABLE catalog) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (catalog) {
    ::google::protobuf::Arena* submessage_arena = catalog->GetArena();
    if (message_arena != submessage_arena) {
      catalog = ::google::protobuf::internal::GetOwnedMessage(message_arena, catalog, submessage_arena);
    }
    set_has_catalog();
    _impl_.body_.catalog_ = catalog;
  }
  // @@protoc_insertion_point(field_set_allocated:pdf_proto.IndirectObject.catalog)
}
void IndirectObject::set_allocated_page_tree(::pdf_proto::PageTree* PROTOBUF_NULLABLE page_tree) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (page_tree) {
    ::google::protobuf::Arena* submessage_arena = page_tree->GetArena();
    if (message_arena != submessage_arena) {
      page_tree = ::google::protobuf::internal::GetOwnedMessage(message_arena, page_tree, submessage_arena);
    }
    set_has_page_tree();
    _impl_.body_.page_tree_ = page_tree;
  }
  // @@protoc_insertion_point(field_set_allocated:pdf_proto.IndirectObject.page_tree)
}
void IndirectObject::set_allocated_page(::pdf_proto::Page* PROTOBUF_NULLABLE page) {
  ::google::protobuf::Arena* message_arena = GetArena();
  clear_body();
  if (page) {
    ::google::protobuf::Arena* submessage_arena = page->GetArena();
    if (message_arena != submessage_arena) {
      page = ::google::protobuf::internal::GetOwnedMessage(message_arena, page, submessage_arena);
    }
    set_has_page();
    _impl_.body_.page_ = page;
  }
  // @@protoc_insertion_point(field_set_allocated:pdf_proto.IndirectObject.page)
}
IndirectObject::IndirectObject(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, IndirectObject_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pdf_proto.IndirectObject)
}
PROTOBUF_NDEBUG_INLINE IndirectObject::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::pdf_proto::IndirectObject& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        body_{},
        _oneof_case_{from._oneof_case_[0]} {}

IndirectObject::IndirectObject(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const IndirectObject& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, IndirectObject_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  IndirectObject* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.number_ = from._impl_.number_;
  switch (body_case()) {
    case BODY_NOT_SET:
      break;
      case kCatalog:
        _impl_.body_.catalog_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.catalog_);
        break;
      case kPageTree:
        _impl_.body_.page_tree_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.page_tree_);
        break;
      case kPage:
        _impl_.body_.page_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.page_);
        break;
  }

  // @@protoc_insertion_point(copy_constructor:pdf_proto.IndirectObject)
}
PROTOBUF_NDEBUG_INLINE IndirectObject::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        body_{},
        _oneof_case_{} {}

inline void IndirectObject::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.number_ = {};
}
IndirectObject::~IndirectObject() {
  // @@protoc_insertion_point(destructor:pdf_proto.IndirectObject)
  SharedDtor(*this);
}
inline void IndirectObject::SharedDtor(MessageLite& self) {
  IndirectObject& this_ = static_cast<IndirectObject&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  if (this_.has_body()) {
    this_.clear_body();
  }
  this_._impl_.~Impl_();
}

void IndirectObject::clear_body() {
// @@protoc_insertion_point(one_of_clear_start:pdf_proto.IndirectObject)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  switch (body_case()) {
    case kCatalog: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.catalog_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.catalog_);
      }
      break;
    }
    case kPageTree: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.page_tree_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.page_tree_);
      }
      break;
    }
    case kPage: {
      if (GetArena() == nullptr) {
        delete _impl_.body_.page_;
      } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
        ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.body_.page_);
      }
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  _impl_._oneof_case_[0] = BODY_NOT_SET;
}


inline void* PROTOBUF_NONNULL IndirectObject::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) IndirectObject(arena);
}
constexpr auto IndirectObject::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(IndirectObject),
                                            alignof(IndirectObject));
}
constexpr auto IndirectObject::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_IndirectObject_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          IndirectObject::IsInitializedImpl,
          &IndirectObject::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<IndirectObject>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &IndirectObject::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<IndirectObject>(), &IndirectObject::ByteSizeLong,
              &IndirectObject::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(IndirectObject, _impl_._cached_size_),
          false,
      },
      &IndirectObject::kDescriptorMethods,
      &descriptor_table_pdf_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull IndirectObject_class_data_ =
        IndirectObject::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
IndirectObject::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&IndirectObject_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(IndirectObject_class_data_.tc_table);
  return IndirectObject_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 4, 3, 0, 2>
IndirectObject::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(IndirectObject, _impl_._has_bits_),
    0, // no _extensions_
    4, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    3,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    IndirectObject_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pdf_proto::IndirectObject>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // required uint32 number = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(IndirectObject, _impl_.number_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(IndirectObject, _impl_.number_)}},
  }}, {{
    65535, 65535
  }}, {{
    // required uint32 number = 1;
    {PROTOBUF_FIELD_OFFSET(IndirectObject, _impl_.number_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // .pdf_proto.Catalog catalog = 2;
    {PROTOBUF_FIELD_OFFSET(IndirectObject, _impl_.body_.catalog_), _Internal::kOneofCaseOffset + 0, 0, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .pdf_proto.PageTree page_tree = 3;
    {PROTOBUF_FIELD_OFFSET(IndirectObject, _impl_.body_.page_tree_), _Internal::kOneofCaseOffset + 0, 1, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
    // .pdf_proto.Page page = 4;
    {PROTOBUF_FIELD_OFFSET(IndirectObject, _impl_.body_.page_), _Internal::kOneofCaseOffset + 0, 2, (0 | ::_fl::kFcOneof | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::pdf_proto::Catalog>()},
      {::_pbi::TcParser::GetTable<::pdf_proto::PageTree>()},
      {::_pbi::TcParser::GetTable<::pdf_proto::Page>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void IndirectObject::Clear() {
// @@protoc_insertion_point(message_clear_start:pdf_proto.IndirectObject)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.number_ = 0u;
  clear_body();
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL IndirectObject::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const IndirectObject& this_ = static_cast<const IndirectObject&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL IndirectObject::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const IndirectObject& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:pdf_proto.IndirectObject)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // required uint32 number = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        1, this_._internal_number(), target);
  }

  switch (this_.body_case()) {
    case kCatalog: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          2, *this_._impl_.body_.catalog_, this_._impl_.body_.catalog_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPageTree: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          3, *this_._impl_.body_.page_tree_, this_._impl_.body_.page_tree_->GetCachedSize(), target,
          stream);
      break;
    }
    case kPage: {
      target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
          4, *this_._impl_.body_.page_, this_._impl_.body_.page_->GetCachedSize(), target,
          stream);
      break;
    }
    default:
      break;
  }
  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pdf_proto.IndirectObject)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t IndirectObject::ByteSizeLong(const MessageLite& base) {
  const IndirectObject& this_ = static_cast<const IndirectObject&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t IndirectObject::ByteSizeLong() const {
  const IndirectObject& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pdf_proto.IndirectObject)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // required uint32 number = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_number());
    }
  }
  switch (this_.body_case()) {
    // .pdf_proto.Catalog catalog = 2;
    case kCatalog: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.catalog_);
      break;
    }
    // .pdf_proto.PageTree page_tree = 3;
    case kPageTree: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.page_tree_);
      break;
    }
    // .pdf_proto.Page page = 4;
    case kPage: {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.body_.page_);
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void IndirectObject::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<IndirectObject*>(&to_msg);
  auto& from = static_cast<const IndirectObject&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:pdf_proto.IndirectObject)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.number_ = from._impl_.number_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  if (const uint32_t oneof_from_case =
          from._impl_._oneof_case_[0]) {
    const uint32_t oneof_to_case = _this->_impl_._oneof_case_[0];
    const bool oneof_needs_init = oneof_to_case != oneof_from_case;
    if (oneof_needs_init) {
      if (oneof_to_case != 0) {
        _this->clear_body();
      }
      _this->_impl_._oneof_case_[0] = oneof_from_case;
    }

    switch (oneof_from_case) {
      case kCatalog: {
        if (oneof_needs_init) {
          _this->_impl_.body_.catalog_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.catalog_);
        } else {
          _this->_impl_.body_.catalog_->MergeFrom(*from._impl_.body_.catalog_);
        }
        break;
      }
      case kPageTree: {
        if (oneof_needs_init) {
          _this->_impl_.body_.page_tree_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.page_tree_);
        } else {
          _this->_impl_.body_.page_tree_->MergeFrom(*from._impl_.body_.page_tree_);
        }
        break;
      }
      case kPage: {
        if (oneof_needs_init) {
          _this->_impl_.body_.page_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.body_.page_);
        } else {
          _this->_impl_.body_.page_->MergeFrom(*from._impl_.body_.page_);
        }
        break;
      }
      case BODY_NOT_SET:
        break;
    }
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void IndirectObject::CopyFrom(const IndirectObject& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:pdf_proto.IndirectObject)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool IndirectObject::IsInitializedImpl(
    const MessageLite& msg) {
  auto& this_ = static_cast<const IndirectObject&>(msg);
  if (_Internal::MissingRequiredFields(this_._impl_._has_bits_)) {
    return false;
  }
  switch (this_.body_case()) {
    case kCatalog: {
      if (this_.body_case() == kCatalog && !this_._impl_.body_.catalog_->IsInitialized())
        return false;
      break;
    }
    case kPageTree: {
      break;
    }
    case kPage: {
      break;
    }
    case BODY_NOT_SET: {
      break;
    }
  }
  return true;
}

void IndirectObject::InternalSwap(IndirectObject* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.number_, other->_impl_.number_);
  swap(_impl_.body_, other->_impl_.body_);
  swap(_impl_._oneof_case_[0], other->_impl_._oneof_case_[0]);
}

::google::protobuf::Metadata IndirectObject::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class PdfDocument::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<PdfDocument>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(PdfDocument, _impl_._has_bits_);
};

PdfDocument::PdfDocument(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PdfDocument_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pdf_proto.PdfDocument)
}
PROTOBUF_NDEBUG_INLINE PdfDocument::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::pdf_proto::PdfDocument& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        pages_{visibility, arena, from.pages_} {}

PdfDocument::PdfDocument(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const PdfDocument& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, PdfDocument_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PdfDocument* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:pdf_proto.PdfDocument)
}
PROTOBUF_NDEBUG_INLINE PdfDocument::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        pages_{visibility, arena} {}

inline void PdfDocument::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
PdfDocument::~PdfDocument() {
  // @@protoc_insertion_point(destructor:pdf_proto.PdfDocument)
  SharedDtor(*this);
}
inline void PdfDocument::SharedDtor(MessageLite& self) {
  PdfDocument& this_ = static_cast<PdfDocument&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL PdfDocument::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) PdfDocument(arena);
}
constexpr auto PdfDocument::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(PdfDocument, _impl_.pages_) +
          decltype(PdfDocument::_impl_.pages_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(PdfDocument), alignof(PdfDocument), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&PdfDocument::PlacementNew_,
                                 sizeof(PdfDocument),
                                 alignof(PdfDocument));
  }
}
constexpr auto PdfDocument::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_PdfDocument_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &PdfDocument::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<PdfDocument>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &PdfDocument::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<PdfDocument>(), &PdfDocument::ByteSizeLong,
              &PdfDocument::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(PdfDocument, _impl_._cached_size_),
          false,
      },
      &PdfDocument::kDescriptorMethods,
      &descriptor_table_pdf_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull PdfDocument_class_data_ =
        PdfDocument::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
PdfDocument::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&PdfDocument_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(PdfDocument_class_data_.tc_table);
  return PdfDocument_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
PdfDocument::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(PdfDocument, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    PdfDocument_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::pdf_proto::PdfDocument>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .pdf_proto.Page pages = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(PdfDocument, _impl_.pages_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .pdf_proto.Page pages = 1;
    {PROTOBUF_FIELD_OFFSET(PdfDocument, _impl_.pages_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::pdf_proto::Page>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void PdfDocument::Clear() {
// @@protoc_insertion_point(message_clear_start:pdf_proto.PdfDocument)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.pages_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL PdfDocument::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const PdfDocument& this_ = static_cast<const PdfDocument&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL PdfDocument::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const PdfDocument& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:pdf_proto.PdfDocument)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .pdf_proto.Page pages = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_pages_size());
         i < n; i++) {
      const auto& repfield = this_._internal_pages().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pdf_proto.PdfDocument)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t PdfDocument::ByteSizeLong(const MessageLite& base) {
  const PdfDocument& this_ = static_cast<const PdfDocument&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t PdfDocument::ByteSizeLong() const {
  const PdfDocument& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:pdf_proto.PdfDocument)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .pdf_proto.Page pages = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_pages_size();
      for (const auto& msg : this_._internal_pages()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void PdfDocument::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<PdfDocument*>(&to_msg);
  auto& from = static_cast<const PdfDocument&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:pdf_proto.PdfDocument)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_pages()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_pages());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void PdfDocument::CopyFrom(const PdfDocument& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:pdf_proto.PdfDocument)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PdfDocument::InternalSwap(PdfDocument* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.pages_.InternalSwap(&other->_impl_.pages_);
}

::google::protobuf::Metadata PdfDocument::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace pdf_proto
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_pdf_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
